### ISSUE TITLE
Dataset  not available in repository

### ISSUE THREAD

**Issue by ghost** [andreabac3/Bot-Gender-Profiling-Pan2019#2]
Hi,

@andreabac3 could you please provide me with the dataset being used for this code? I am trying to reproduce the outputs for research.

**Comment by andreabac3** [comment]
Hi @bilaltahir2178 , 
I cannot provide the dataset because is copyright protected, you should ask to PAN organization the access to it.

For reproducibility remember that:
- Seed: fixing the seed is not enough because changing the architecture and the lib version you don't have guarantee on reproducibility.
- As stated in the readme, the code is not 1:1 with the used in the PAN competition because we improved it after the competition finding better hyperparameters and testing it in other dataset, but the performance not change too much. Other datasets I mean the full version of the pan dataset which was not provided during the competition.

For any other question feel free to contact me.

Kind regards,
Andrea Bacciu

**Comment by ghost** [comment]
Thanks for your guidance. I'll contact them :)
